public enum GameClientPacketType : byte
{
    ProtocolVersion = 0x00,
    RequestMoveDirection = 0x02,
    EnterWorld = 0x03,
    RequestAction = 0x04,
    RequestSetTarget = 0x05,
    AuthRequest = 0x08,
    Disconnect = 0x09,
    RequestAttack = 0x0a,
    RequestCharCreate = 0x0b,
    RequestCharDelete = 0x0c,
    RequestCharSelect = 0x0d,
    RequestInventoryOpen = 0x0f,
    RequestInventoryUpdateOrder = 0x10,
    RequestDropItem = 0x12,
    UseItem = 0x14,
    RequestSellItem = 0x1e,
    RequestBuyItem = 0x1f,
    RequestBypassToServer = 0x21,
    RequestMagicSkillUse = 0x2f,
    Appearing = 0x30,
    RequestShortcutReg = 0x33,
    RequestShortcutDel = 0x35,
    RequestCancel = 0x37,
    SendMessage = 0x38,
    RequestActionUse = 0x45,
    RequestRestart = 0x46,
    ValidatePosition = 0x48,
    RequestDestroyItem = 0x59,
    GMCommand = 0x5b,
    RequestCharRestore = 0x62,
    RequestRestartPoint = 0x6d,
    DoubleOPCode = 0xd0,
    RequestSkillList = 0x3f,
    RequestAcquireSkillInfo = 0x6b,
    RequestAcquireSkill = 0x6c,


    //deprecated
    Ping = 0xF0,
    RequestRotate = 0xF3,
    RequestAnim = 0xF4,
}
