public enum GameServerPacketType : int
{
    VersionCheck = 0x00,
    ObjectMoveTo = 0x01,
    UserInfo = 0x03,
    PlayerInfo = 0x04,
    Attack = 0x05,
    DoDie = 0x06,
    Revive = 0x07,
    ActionAllowed = 0x08,
    StatusUpdate = 0x0e,
    NpcHtml = 0x0f,
    SellList = 0x10,
    BuyList = 0x11,
    RemoveObject = 0x12,
    CharSelectionInfo = 0x13,
    LoginFail = 0x14,
    CharSelected = 0x15,
    NpcInfo = 0x16,
    CharCreateOk = 0x19,
    InventoryUpdate = 0x27,
    CharCreateFail = 0x1a,
    InventoryItemList = 0x1b,
    CharDeleteOk = 0x23,
    CharDeleteFail = 0x24,
    ActionFailed = 0x25,
    ServerClose = 0x26,
    TeleportToLocation = 0x28,
    EntityTargetSet = 0x29,
    TargetUnselected = 0x2a,
    FightStanceStart = 0x2b,
    FightStanceStop = 0x2c,
    SocialAction = 0x2d,
    ChangeMoveType = 0x2e,
    ChangeWaitType = 0x2f,
    ShortcutRegister = 0x44,
    ShortcutInit = 0x45,
    ShortcutDelete = 0x46,
    StopMove = 0x47,
    MagicSkillUse = 0x48,
    MagicSkillCanceled = 0x49,
    CreatureSay = 0x4a,
    SkillList = 0x58,
    RestartReponse = 0x5F,
    ValidateLocation = 0x61,
    SystemMessage = 0x64,
    SetupGauge = 0x6d,
    MagicSkillLaunched = 0x76,
    LeaveWorld = 0x7e,
    AbnormalStatusUpdate = 0x7f,
    AcquireSkillLearnList = 0x8a,
    AcquireSkillLearnInfo = 0x8b,
    AcquireSkillLearnDone = 0x8e,
    MyTargetSet = 0xA6,
    SkillCoolTime = 0xC1,
    ObjectMoveDirection = 0xC6,
    RelationChanged = 0xCE,
    PartyEffect = 0xee,
    EtcStatusUpdate = 0xF3,
    ShortBuffStatusUpdate = 0xF4,
    ExAutoSoulshot = 0xFE,



    // Deprecated / need to implement or removed
    ObjectPosition = 0xFF7,
    ObjectRotation = 0xFF9,
    ObjectAnimation = 0xFFA,
    GameTime = 0xFD0,

    Ping = 0xFE1,

}
