public enum Event
{
    THINK,
    DEAD,
    ARRIVED,
    MOVE_INPUT_PRESSED,
    ATTACKED,
    FORGET_OBJECT,
    READY_TO_ACT,
    CANCEL,
    TARGET_REACHED,
    ACTION_ALLOWED,
    ACTION_DENIED,
    MOVE_TYPE_UPDATED
}
