public enum Intention
{
    INTENTION_IDLE,
    INTENTION_WAITING,
    INTENTION_MOVE,
    INTENTION_MOVE_TO,
    INTENTION_ATTACK,
    INTENTION_INTERACT,
    INTENTION_FOLLOW,
    INTENTION_SIT,
    INTENTION_STAND,
    INTENTION_SKILL,
    INTENTION_JUMP
}
