public enum GameState : byte
{
    STARTING_GAME,
    ENTERING_WORLD,
    LOGIN_SCREEN,
    LOGIN_CONNECTED,
    LOGIN_AUTHED,
    CHAR_SELECT,
    CHAR_CREATION,
    IN_GAME,
    RESTARTING,
    DISONNECTING,
    TELEPORTING
}