public enum GameEvent
{
    CONNECT_ALLOWED,
    AUTH_ALLOWED,
    SERVER_LIST_RECEIVED,
    LOGIN_DISCONNECTED,
    GAME_DISCONNECTED,
    CHAR_CREATED,
    CHAR_SELECTED,
    CHAR_LOADED,
    RETURN,
    LOADING_STARTED,
    LOADING_COMPLETE,
    PLAY_ALLOWED
}