public enum ELightCoordSystem
{
    PTCS_INDEPENDENT = 0,
    PTCS_RELATIVE = 1,
    PTCS_ABSOLUTE = 2,
    PTCS_RELATIVEROTATION = 3,
    PTCS_SPRAY = 4,
    PTCS_RELATIVEPOSITION = 5,
    PTCS_SCREENABSOLUTE = 6,
    PTCS_SCREENRELATIVE = 7,
    PTCS_MAX = 8
}